apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: event-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "api-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["api-service:8080"]

      - job_name: "analysis-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["analysis-service:8081"]
          
      - job_name: "cadvisor"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["cadvisor:8080"]