apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: event-platform
spec:
  accessModes:
    - ReadWriteMany

  storageClassName: ""

  resources:
    requests:
      storage: 5Gi

  volumeName: uploads-pv