spring.application.name=demo
server.port=8081
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=gpt-oss:120b-cloud
spring.ai.retry.max-attempts=1
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text

spring.kafka.consumer.group-id=analysis-workers
spring.kafka.consumer.auto-offset-reset=earliest
 

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.ai.vectorstore.qdrant.host=${QDRANT_HOST:localhost}
spring.ai.vectorstore.qdrant.port=${QDRANT_PORT:6334}
spring.ai.vectorstore.qdrant.collection-name=document_chunks
spring.ai.vectorstore.qdrant.initialize-schema=true

# Document chunking
app.document.chunk-size=800
app.document.min-chunk-size-chars=350
app.document.min-chunk-length-to-embed=10
app.document.max-num-chunks=5000

# Vector search
app.vector-search.top-k=2
app.vector-search.similarity-threshold=0.4

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
app.upload.dir=${APP_UPLOAD_DIR:C:/Event driven ai platform/uploads}